project:
  type: book

  output-dir: output/

book:
  title: metasurvey
  subtitle: Paquete de R para el procesamiento de encuestas por muestreo con generación de recetas mediante metaprogramación y estimación de varianzas.
  author:
    name: Mauro Loprete
    url: www.mauroloprete.com
  downloads: [pdf]
  reader-mode: true
  language: spanish
  abstract: "El presente trabajo presenta *metasurvey*, un paquete de R diseñado para mejorar el procesamiento de encuestas por muestreo y la estimación de parámetros poblacionales junto con sus respectivos errores estándar. Utiliza meta-programación y técnicas de remuestreo, para evaluar la incertidumbre de las estimaciones de los diferentes parámetros y fomentar la reproducibilidad. A diferencia de otras bibliotecas, *metasurvey* combina flexibilidad mediante meta-programación con las capacidades de procesamiento de encuestas del paquete *survey*. Los objetivos incluyen proporcionar una herramienta útil, incorporar técnicas de remuestreo para usuarios no expertos, permitir la generación de 'recetas' personalizadas, y fomentar la contribución de la comunidad. Se destaca como alternativa a paquetes propietarios, enfocándose en la transparencia y reproducibilidad para mejorar la confiabilidad de las estimaciones poblacionales."
  chapters:
    - index.qmd
    - chapters/chapter1.qmd
    - chapters/chapter2.qmd
    - chapters/chapter3.qmd
    - chapters/chapter5.qmd
    - chapters/chapter6.qmd
    - chapters/chapter7.qmd
    - chapters/bibliography.qmd
  

  site-url: https://github.com/metaSurveyR/metasurvey
  repo-url: https://github.com/metaSurveyR/metasurvey
  repo-actions: [edit, source, issue]
  search: true
  image: images/logo.png

thesis:
  supervisor: 
    name: Dra. Natalia da Silva
  degree-name: Licenciado en Estadística
  university: Universidad de la República
  department: Instituto de Estadística
  date: Diciembre de 2024
  group: I
  faculty: Facultad de Ciencias Económicas y de Administración
  quotation:
    text: "wwww"
    attribution: "wwww"
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"

bibliography: [chapters/references.bib]

execute:
  echo: false
  code-overflow: wrap
  cache: true
  tidy: 'styler'
  message: false
  tbl-pos: 'H'
  fig-pos: 'H'
  lst-pos: 'H'

crossref: 
  sec-prefix: 'Capítulo'
  fig-prefix: 'Figura'
  tbl-prefix: 'Tabla'
  lst-prefix: 'Código'
  lol-title: "Lista de Códigos"
  lst-title: "Código"
  fig-title: "Figura"
  tbl-title: "Tabla"
  appendix-title: "Apéndice"
  appendix-delim: ":"




# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: blue
    toclinkcolor: blue
    citecolor: blue
    linkcolor: blue
    colorlinks: true
    toc-depth: 3
    citation_package: biblatex
  html:
    theme: 
      - cosmo
      - style.scss
    lang:  es
    split_bib: no
    toc-depth: 3
    code:
      highlight: pygments
      theme: monokai
